SELECT TOP (1000) [FQDNServerName]
      ,[ShortServerName]
      ,[Windows Version]
      ,[CPU]
      ,[Memory_MB]
      ,[Windows Service Pack]
      ,[ID]
  FROM [ProjectData].[dbo].[SQLInfo_ServerData]

SELECT TOP (1000) [ID]
      ,[dbid]
      ,[dbName]
      ,[Status]
      ,[User access]
      ,[Recovery model]
      ,[compatibility level]
      ,[Physical_Name]
      ,[Creation_date]
  FROM [ProjectData].[dbo].[SQLInfo_SQL_DB_Data]

  SELECT TOP (1000) [ID]
      ,[FQDNServerName]
      ,[ShortServerName]
      ,[SQLServerRelease]
      ,[ServicePackVersion]
      ,[KBArticle]
      ,[BuildNumber]
      ,[SQLServerVersion]
      ,[Product_Version]
      ,[Product_Level]
      ,[Collation_Type]
      ,[IsClustered?]
      ,[Authentication Mode]
  FROM [ProjectData].[dbo].[SQLInfo_SQLServerData]