USE MASTER
GO
ALTER DATABASE [SomersetAandE]
SET ENCRYPTION OFF
GO

USE master;
 
ALTER MASTER KEY
DROP ENCRYPTION BY SERVICE MASTER KEY
GO

USE [SomersetAandE];
DROP DATABASE ENCRYPTION KEY;

USE master;
DROP CERTIFICATE BIS_SP09_TDE_Certificate;

USE master;
DROP MASTER KEY;
